/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — o processo está de pé */
        get: operations["SaudeController_saude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pronto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — dependências respondem */
        get: operations["SaudeController_pronto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entrada da equipe da escola (e-mail e senha) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/convite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Entrada da família por convite da escola
         * @description Sem senha: a sessão é presa ao device e dura meses. O responsável instala o app uma vez e não vê login de novo.
         */
        post: operations["AuthController_convite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova o access token (rotaciona o refresh) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessão do device atual */
        post: operations["AuthController_sair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da sessão atual */
        get: operations["AuthController_eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfis disponíveis para experimentar
         * @description Só responde com DEMO_MODE=true. Alimenta a tela de entrada dos dois PWAs.
         */
        get: operations["DemoController_perfis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entra como um perfil de demonstração, sem cadastro */
        post: operations["DemoController_entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escola": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da escola da sessão */
        get: operations["EscolasController_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza dados cadastrais da escola */
        patch: operations["EscolasController_atualizar"];
        trace?: never;
    };
    "/v1/escola/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Painel da gestão: números do dia */
        get: operations["EscolasController_resumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/equipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equipe da escola */
        get: operations["UsuariosController_equipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{criancaId}/responsaveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Responsáveis vinculados a uma criança */
        get: operations["UsuariosController_responsaveis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Convites emitidos */
        get: operations["UsuariosController_convites"];
        put?: never;
        /**
         * Gera convite de acesso para um responsável
         * @description O código vira QR no mural — é o início do funil de instalação do app.
         */
        post: operations["UsuariosController_criarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/familias-sem-acesso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crianças cujas famílias ainda não ativaram o app
         * @description Lista de cobrança da secretaria. Sem push, a família fica no escuro — e a escola cancela.
         */
        get: operations["UsuariosController_familiasSemAcesso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turmas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turmas do usuário (gestão vê todas) */
        get: operations["TurmasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turmas/{id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grade do dia — a tela principal do educador
         * @description Crianças da turma com presença, registros já feitos e pendências. É o que sustenta o registro em lote.
         */
        get: operations["TurmasController_grade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/minhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crianças vinculadas ao responsável logado */
        get: operations["CriancasController_minhas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{id}/dia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O dia da criança — a tela principal do app da família
         * @description Linha do tempo em frases prontas, mais um resumo de uma linha para o card.
         */
        get: operations["CriancasController_dia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra entrada (ou falta) da criança */
        post: operations["PresencasController_checkin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra saída da criança
         * @description Confere quem retira contra vínculos e autorizados — recusa quem não está na lista.
         */
        post: operations["PresencasController_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/turma/{turmaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presenças da turma no dia */
        get: operations["PresencasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registros/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sincroniza a fila offline do educador
         * @description Responde item a item. Um erro isolado não derruba o lote, e "duplicado" é sucesso — é o reenvio de quem estava sem rede.
         */
        post: operations["RegistrosController_sincronizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comunicados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comunicados publicados pela escola */
        get: operations["ComunicadosController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comunicados/{id}/lido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma leitura (a escola cobra por essa taxa) */
        post: operations["ComunicadosController_marcarLido"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cardapios/semana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cardápio da semana (segunda a sexta) */
        get: operations["CardapiosController_semana"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginEquipeDto: {
            /** @example ana.educadora@diadeles.com.br */
            email: string;
            /** @example demo1234 */
            senha: string;
            /** @example Motorola Edge 30 */
            deviceLabel?: string;
        };
        UsuarioSessaoDto: {
            id: string;
            nome: string;
            email?: string | null;
            papeis: string[];
            escolaId: string;
            escolaNome: string;
            /** @enum {string} */
            app: "educador" | "responsavel";
        };
        SessaoDto: {
            accessToken: string;
            refreshToken: string;
            /** @description Segundos até o access token expirar */
            expiraEm: number;
            usuario: components["schemas"]["UsuarioSessaoDto"];
        };
        UsarConviteDto: {
            /**
             * @description Código do convite entregue pela escola
             * @example SOF-4K2P
             */
            codigo: string;
            /** @example 11988887777 */
            celular: string;
            /** @example Marina Prado */
            nome?: string;
            /** @example iPhone 13 */
            deviceLabel?: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        DemoLoginDto: {
            /**
             * @example educadora
             * @enum {string}
             */
            perfil: "educadora" | "coordenadora" | "gestora" | "responsavel";
        };
        EscolaDto: {
            id: string;
            nome: string;
            slug: string;
            cnpj?: string | null;
            telefone?: string | null;
            email?: string | null;
            timezone: string;
            /** @description Módulos ativos e campos de rotina habilitados */
            configuracoes: Record<string, never>;
        };
        ResumoEscolaDto: {
            escola: components["schemas"]["EscolaDto"];
            /** @description Crianças com matrícula ativa */
            criancasAtivas: number;
            turmas: number;
            educadores: number;
            /** @description Famílias com ao menos um responsável vinculado */
            familiasVinculadas: number;
            /** @description Presentes hoje */
            presentesHoje: number;
            /** @description Ausentes hoje */
            ausentesHoje: number;
            /** @description Registros de rotina lançados hoje */
            registrosHoje: number;
        };
        AtualizarEscolaDto: {
            nome?: string;
            telefone?: string;
            email?: string;
        };
        MembroEquipeDto: {
            id: string;
            nome: string;
            email?: string | null;
            papeis: ("SUPER_ADMIN" | "REDE_ADMIN" | "GESTOR" | "COORDENADOR" | "EDUCADOR" | "AUXILIAR" | "RESPONSAVEL")[];
            ativo: boolean;
            /** Format: date-time */
            ultimoAcesso?: string | null;
            /** @description Turmas em que atua */
            turmas: string[];
        };
        ResponsavelDto: {
            id: string;
            nome: string;
            celular?: string | null;
            /** @enum {string} */
            tipo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            podeRetirar: boolean;
            bloqueado: boolean;
            /** @description Já instalou e acessou o app alguma vez */
            ativou: boolean;
        };
        CriarConviteDto: {
            /** @description Criança a que o responsável será vinculado */
            criancaId: string;
            /** @enum {string} */
            tipoVinculo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            nome?: string;
            celular?: string;
        };
        ConviteDto: {
            id: string;
            /** @example SOF-4K2P */
            codigo: string;
            criancaId: string;
            criancaNome: string;
            /** @enum {string} */
            tipoVinculo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            /** Format: date-time */
            expiraEm: string;
            /** Format: date-time */
            usadoEm?: string | null;
            /** @description Link pronto para o QR do mural */
            link: string;
        };
        TurmaDto: {
            id: string;
            nome: string;
            /** @enum {string} */
            grupoEtario: "BEBES" | "CRIANCAS_BEM_PEQUENAS" | "CRIANCAS_PEQUENAS";
            /** @example integral */
            turno: string;
            cor?: string | null;
            criancasAtivas: number;
            educadores: string[];
        };
        RegistroResumoDto: {
            id: string;
            /** @enum {string} */
            tipo: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** Format: date-time */
            ocorridoEm: string;
            dados: Record<string, never>;
            observacao?: string | null;
        };
        CriancaNaGradeDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2a 4m */
            idade: string;
            /** @description Alergias — sempre em destaque na UI, é o dado que não pode passar batido */
            alergias: string[];
            restricoesAlimentares: string[];
            /** @description Ainda não teve entrada registrada hoje */
            semPresenca: boolean;
            presente: boolean;
            ausente: boolean;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            registros: components["schemas"]["RegistroResumoDto"][];
            /** @description Tipos ainda não registrados hoje — alimenta a tela de fechamento do turno */
            pendencias: ("ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO")[];
            /** @description Tem medicação autorizada e vigente para hoje */
            temMedicacaoHoje: boolean;
        };
        GradeDoDiaDto: {
            turma: components["schemas"]["TurmaDto"];
            /** @example 2026-08-02 */
            data: string;
            criancas: components["schemas"]["CriancaNaGradeDto"][];
            /** @description Crianças com todos os tipos esperados já registrados */
            completas: number;
        };
        CriancaResumoDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2a 4m */
            idade: string;
            turmaNome?: string | null;
            alergias: string[];
        };
        ItemTimelineDto: {
            id: string;
            /** @enum {string} */
            categoria: "ENTRADA" | "SAIDA" | "REGISTRO" | "OCORRENCIA" | "MEDICACAO";
            /** @enum {string} */
            tipo?: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** Format: date-time */
            ocorridoEm: string;
            /** @description Frase pronta para exibição — a família não lê enum */
            titulo: string;
            detalhe?: string | null;
            dados: Record<string, never>;
        };
        DiaDaCriancaDto: {
            crianca: components["schemas"]["CriancaResumoDto"];
            /** @example 2026-08-02 */
            data: string;
            presente: boolean;
            ausente: boolean;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            timeline: components["schemas"]["ItemTimelineDto"][];
            /** @description Resumo em uma frase, para o card e a notificação */
            resumo: string;
        };
        CheckinDto: {
            criancaId: string;
            turmaId: string;
            /** @description Quem entregou a criança na porta */
            entreguePorNome?: string;
            /** @description Marca falta em vez de presença */
            ausente?: boolean;
            justificativa?: string;
        };
        PresencaDto: {
            id: string;
            criancaId: string;
            /** @example 2026-08-02 */
            data: string;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            ausente: boolean;
            entreguePorNome?: string | null;
            retiradoPorNome?: string | null;
        };
        CheckoutDto: {
            criancaId: string;
            /** @description Quem retirou — conferido contra a lista de autorizados */
            retiradoPorNome: string;
            retiradoPorVinculoId?: string;
            retiradoPorAutorizadoId?: string;
        };
        EnvelopeRegistroDto: {
            /** @description UUID gerado no cliente — chave de idempotência */
            clientId: string;
            criancaId: string;
            turmaId: string;
            /** @enum {string} */
            tipo: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** @example 2026-08-02T14:30:00.000Z */
            ocorridoEm: string;
            /** @description Payload específico do tipo, validado por Zod (ver schemas/) */
            dados: Record<string, never>;
            observacao?: string | null;
        };
        LoteSincronizacaoDto: {
            itens: components["schemas"]["EnvelopeRegistroDto"][];
        };
        ResultadoItemDto: {
            clientId: string;
            /**
             * @description "duplicado" é sucesso: é o reenvio normal de quem estava offline
             * @enum {string}
             */
            status: "criado" | "duplicado" | "erro";
            id?: string;
            codigo?: string;
            mensagem?: string;
        };
        ResultadoSincronizacaoDto: {
            resultados: components["schemas"]["ResultadoItemDto"][];
            criados: number;
            duplicados: number;
            erros: number;
        };
        ComunicadoDto: {
            id: string;
            titulo: string;
            corpo: string;
            /** Format: date-time */
            publicadoEm?: string | null;
            exigeCiencia: boolean;
            lido: boolean;
            /** @description Confirmações de leitura — o que a escola cobra */
            totalLeituras: number;
        };
        MarcarLidoDto: {
            criancaId: string;
        };
        CardapioDto: {
            id: string;
            /** @example 2026-08-03 */
            data: string;
            /**
             * @example {
             *       "lancheManha": "Fruta da estação",
             *       "almoco": "Arroz, feijão, frango e legumes"
             *     }
             */
            refeicoes: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaudeController_saude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaudeController_pronto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEquipeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_convite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsarConviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSessaoDto"];
                };
            };
        };
    };
    DemoController_perfis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DemoController_entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    EscolasController_buscar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscolaDto"];
                };
            };
        };
    };
    EscolasController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarEscolaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscolaDto"];
                };
            };
        };
    };
    EscolasController_resumo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoEscolaDto"];
                };
            };
        };
    };
    UsuariosController_equipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembroEquipeDto"][];
                };
            };
        };
    };
    UsuariosController_responsaveis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criancaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsavelDto"][];
                };
            };
        };
    };
    UsuariosController_convites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteDto"][];
                };
            };
        };
    };
    UsuariosController_criarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarConviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteDto"];
                };
            };
        };
    };
    UsuariosController_familiasSemAcesso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TurmasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurmaDto"][];
                };
            };
        };
    };
    TurmasController_grade: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDoDiaDto"];
                };
            };
        };
    };
    CriancasController_minhas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriancaResumoDto"][];
                };
            };
        };
    };
    CriancasController_dia: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaDaCriancaDto"];
                };
            };
        };
    };
    PresencasController_checkin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"];
                };
            };
        };
    };
    PresencasController_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"];
                };
            };
        };
    };
    PresencasController_listar: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                turmaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"][];
                };
            };
        };
    };
    RegistrosController_sincronizar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteSincronizacaoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoSincronizacaoDto"];
                };
            };
        };
    };
    ComunicadosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunicadoDto"][];
                };
            };
        };
    };
    ComunicadosController_marcarLido: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarLidoDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardapiosController_semana: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardapioDto"][];
                };
            };
        };
    };
}
