/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — o processo está de pé */
        get: operations["SaudeController_saude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pronto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — dependências respondem */
        get: operations["SaudeController_pronto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entrada da equipe da escola (e-mail e senha) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/convite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Entrada da família por convite da escola
         * @description Sem senha: a sessão é presa ao device e dura meses. O responsável instala o app uma vez e não vê login de novo.
         */
        post: operations["AuthController_convite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova o access token (rotaciona o refresh) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessão do device atual */
        post: operations["AuthController_sair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da sessão atual */
        get: operations["AuthController_eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfis disponíveis para experimentar
         * @description Só responde com DEMO_MODE=true. Alimenta a tela de entrada dos dois PWAs, e é onde a escola de demonstração é remontada se o dia dela já passou.
         */
        get: operations["DemoController_perfis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entra como um perfil de demonstração, sem cadastro */
        post: operations["DemoController_entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/escola": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados da escola da sessão */
        get: operations["EscolasController_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza dados cadastrais da escola */
        patch: operations["EscolasController_atualizar"];
        trace?: never;
    };
    "/v1/escola/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Painel da gestão: números do dia */
        get: operations["EscolasController_resumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/equipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Equipe da escola */
        get: operations["UsuariosController_equipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{criancaId}/responsaveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Responsáveis vinculados a uma criança */
        get: operations["UsuariosController_responsaveis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Convites emitidos */
        get: operations["UsuariosController_convites"];
        put?: never;
        /**
         * Gera convite de acesso para um responsável
         * @description O código vira QR no mural — é o início do funil de instalação do app.
         */
        post: operations["UsuariosController_criarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/familias-sem-acesso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crianças cujas famílias ainda não ativaram o app
         * @description Lista de cobrança da secretaria. Sem push, a família fica no escuro — e a escola cancela.
         */
        get: operations["UsuariosController_familiasSemAcesso"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turmas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turmas do usuário (gestão vê todas) */
        get: operations["TurmasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turmas/{id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grade do dia — a tela principal do educador
         * @description Crianças da turma com presença, registros já feitos e pendências. É o que sustenta o registro em lote.
         */
        get: operations["TurmasController_grade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/turmas/{id}/fechar-turno": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fecha o turno e envia o resumo do dia às famílias
         * @description Cada responsável com vínculo ativo recebe o dia da criança em uma frase. Fechar de novo no mesmo dia não reenvia — quem já foi avisado é contado em `jaAvisadas`.
         */
        post: operations["TurmasController_fecharTurno"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/chave-publica": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chave pública VAPID para o navegador se inscrever */
        get: operations["NotificacoesController_chavePublica"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra a inscrição de push deste aparelho
         * @description Idempotente pelo endpoint — o navegador o rotaciona por conta própria.
         */
        post: operations["NotificacoesController_registrarDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/devices/remover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desliga os avisos deste aparelho */
        post: operations["NotificacoesController_removerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caixa de avisos dentro do app
         * @description O canal externo avisa, mas o app é a fonte de verdade: tudo o que foi notificado está aqui, mesmo que o push e o e-mail tenham falhado.
         */
        get: operations["NotificacoesController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/{id}/lida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca um aviso como lido */
        post: operations["NotificacoesController_marcarLida"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/lidas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca todos os avisos como lidos */
        post: operations["NotificacoesController_marcarTodasLidas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificacoes/teste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envia um aviso de teste para o próprio usuário */
        post: operations["NotificacoesController_teste"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/minhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crianças vinculadas ao responsável logado */
        get: operations["CriancasController_minhas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crianças da escola, para o cadastro da secretaria */
        get: operations["CriancasController_listar"];
        put?: never;
        /**
         * Cadastra uma criança
         * @description Com `turmaId`, já sai matriculada — sem turma ela não aparece na grade de ninguém.
         */
        post: operations["CriancasController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha da criança
         * @description Dados, responsáveis, autorizados a retirar, medicação vigente e consentimentos. A equipe vê qualquer criança da escola; o responsável, só as suas.
         */
        get: operations["CriancasController_ficha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza o cadastro da criança */
        patch: operations["CriancasController_atualizar"];
        trace?: never;
    };
    "/v1/criancas/{id}/arquivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arquiva a criança
         * @description Nunca apaga: registro pedagógico tem retenção de 5 anos e excluir levaria junto a rotina, as ocorrências e as presenças.
         */
        post: operations["CriancasController_arquivar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{id}/desarquivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Traz a criança de volta ao cadastro ativo */
        post: operations["CriancasController_desarquivar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{id}/dia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O dia da criança — a tela principal do app da família
         * @description Linha do tempo em frases prontas, mais um resumo de uma linha para o card.
         */
        get: operations["CriancasController_dia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/criancas/{id}/consentimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Concede ou revoga o uso de imagem da criança
         * @description Granular por escopo e revogável a qualquer momento (LGPD art. 14). A resposta anterior não é apagada — é revogada e mantida como prova de conformidade.
         */
        post: operations["CriancasController_decidirConsentimento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matriculas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matricula a criança numa turma
         * @description Se ela já estiver ativa em outra, a anterior é encerrada na mesma transação e a resposta vem com `transferida: true`.
         */
        post: operations["MatriculasController_matricular"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matriculas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tranca, encerra ou reabre a matrícula */
        patch: operations["MatriculasController_atualizar"];
        trace?: never;
    };
    "/v1/matriculas/crianca/{criancaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de matrículas da criança */
        get: operations["MatriculasController_historico"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra entrada (ou falta) da criança */
        post: operations["PresencasController_checkin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra saída da criança
         * @description Confere quem retira contra vínculos e autorizados — recusa quem não está na lista.
         */
        post: operations["PresencasController_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presencas/turma/{turmaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presenças da turma no dia */
        get: operations["PresencasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registros/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sincroniza a fila offline do educador
         * @description Responde item a item. Um erro isolado não derruba o lote, e "duplicado" é sucesso — é o reenvio de quem estava sem rede.
         */
        post: operations["RegistrosController_sincronizar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comunicados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comunicados publicados pela escola */
        get: operations["ComunicadosController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comunicados/{id}/lido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma leitura (a escola cobra por essa taxa) */
        post: operations["ComunicadosController_marcarLido"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cardapios/semana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cardápio da semana (segunda a sexta) */
        get: operations["CardapiosController_semana"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ocorrencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ocorrências do dia, da turma ou da escola inteira */
        get: operations["OcorrenciasController_listar"];
        put?: never;
        /**
         * Registra uma ocorrência e avisa a família
         * @description Idempotente pelo `clientId`. Gravidade GRAVE sai por push **e** e-mail; as demais seguem o roteamento normal de canal.
         */
        post: operations["OcorrenciasController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ocorrencias/{id}/ciente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responsável confirma que leu a ocorrência
         * @description A primeira confirmação é a que vale — reabrir a tela não reescreve a hora.
         */
        post: operations["OcorrenciasController_confirmarCiencia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginEquipeDto: {
            /** @example ana.educadora@diadeles.com.br */
            email: string;
            /** @example demo1234 */
            senha: string;
            /** @example Motorola Edge 30 */
            deviceLabel?: string;
        };
        UsuarioSessaoDto: {
            id: string;
            nome: string;
            email?: string | null;
            papeis: string[];
            escolaId: string;
            escolaNome: string;
            /** @enum {string} */
            app: "educador" | "responsavel";
        };
        SessaoDto: {
            accessToken: string;
            refreshToken: string;
            /** @description Segundos até o access token expirar */
            expiraEm: number;
            usuario: components["schemas"]["UsuarioSessaoDto"];
        };
        UsarConviteDto: {
            /**
             * @description Código do convite entregue pela escola
             * @example SOF-4K2P
             */
            codigo: string;
            /** @example 11988887777 */
            celular: string;
            /** @example Marina Prado */
            nome?: string;
            /** @example iPhone 13 */
            deviceLabel?: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        DemoLoginDto: {
            /**
             * @example educadora
             * @enum {string}
             */
            perfil: "educadora" | "coordenadora" | "gestora" | "responsavel";
        };
        EscolaDto: {
            id: string;
            nome: string;
            slug: string;
            cnpj?: string | null;
            telefone?: string | null;
            email?: string | null;
            timezone: string;
            /** @description Módulos ativos e campos de rotina habilitados */
            configuracoes: Record<string, never>;
        };
        ResumoEscolaDto: {
            escola: components["schemas"]["EscolaDto"];
            /** @description Crianças com matrícula ativa */
            criancasAtivas: number;
            turmas: number;
            educadores: number;
            /** @description Famílias com ao menos um responsável vinculado */
            familiasVinculadas: number;
            /** @description Presentes hoje */
            presentesHoje: number;
            /** @description Ausentes hoje */
            ausentesHoje: number;
            /** @description Registros de rotina lançados hoje */
            registrosHoje: number;
        };
        AtualizarEscolaDto: {
            nome?: string;
            telefone?: string;
            email?: string;
        };
        MembroEquipeDto: {
            id: string;
            nome: string;
            email?: string | null;
            papeis: ("SUPER_ADMIN" | "REDE_ADMIN" | "GESTOR" | "COORDENADOR" | "EDUCADOR" | "AUXILIAR" | "RESPONSAVEL")[];
            ativo: boolean;
            /** Format: date-time */
            ultimoAcesso?: string | null;
            /** @description Turmas em que atua */
            turmas: string[];
        };
        ResponsavelDto: {
            id: string;
            nome: string;
            celular?: string | null;
            /** @enum {string} */
            tipo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            podeRetirar: boolean;
            bloqueado: boolean;
            /** @description Já instalou e acessou o app alguma vez */
            ativou: boolean;
        };
        CriarConviteDto: {
            /** @description Criança a que o responsável será vinculado */
            criancaId: string;
            /** @enum {string} */
            tipoVinculo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            nome?: string;
            celular?: string;
        };
        ConviteDto: {
            id: string;
            /** @example SOF-4K2P */
            codigo: string;
            criancaId: string;
            criancaNome: string;
            /** @enum {string} */
            tipoVinculo: "MAE" | "PAI" | "AVO" | "TIO" | "PADRASTO_MADRASTA" | "RESPONSAVEL_LEGAL" | "OUTRO";
            /** Format: date-time */
            expiraEm: string;
            /** Format: date-time */
            usadoEm?: string | null;
            /** @description Link pronto para o QR do mural */
            link: string;
        };
        CriancaSemAcessoDto: {
            id: string;
            nome: string;
        };
        TurmaDto: {
            id: string;
            nome: string;
            /** @enum {string} */
            grupoEtario: "BEBES" | "CRIANCAS_BEM_PEQUENAS" | "CRIANCAS_PEQUENAS";
            /** @example integral */
            turno: string;
            cor?: string | null;
            criancasAtivas: number;
            educadores: string[];
        };
        RegistroResumoDto: {
            id: string;
            /** @enum {string} */
            tipo: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** Format: date-time */
            ocorridoEm: string;
            dados: Record<string, never>;
            observacao?: string | null;
        };
        CriancaNaGradeDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2a 4m */
            idade: string;
            /** @description Alergias — sempre em destaque na UI, é o dado que não pode passar batido */
            alergias: string[];
            restricoesAlimentares: string[];
            /** @description Ainda não teve entrada registrada hoje */
            semPresenca: boolean;
            presente: boolean;
            ausente: boolean;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            registros: components["schemas"]["RegistroResumoDto"][];
            /** @description Tipos ainda não registrados hoje — alimenta a tela de fechamento do turno */
            pendencias: ("ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO")[];
            /** @description Tem medicação autorizada e vigente para hoje */
            temMedicacaoHoje: boolean;
        };
        GradeDoDiaDto: {
            turma: components["schemas"]["TurmaDto"];
            /** @example 2026-08-02 */
            data: string;
            criancas: components["schemas"]["CriancaNaGradeDto"][];
            /** @description Crianças com todos os tipos esperados já registrados */
            completas: number;
        };
        FechamentoDto: {
            /** @example 2026-08-02 */
            data: string;
            /** @description Crianças presentes hoje — as ausentes não geram resumo */
            criancas: number;
            /** @description Responsáveis que receberam o resumo agora */
            familiasAvisadas: number;
            /** @description Já haviam recebido o resumo hoje; não recebem de novo */
            jaAvisadas: number;
            /** @description Crianças presentes sem nenhum responsável com acesso ao app */
            semResponsavel: number;
        };
        ChavePublicaDto: {
            /** @description Chave pública VAPID. `null` quando o push não está configurado no servidor. */
            chavePublica: string | null;
        };
        RegistrarDeviceDto: {
            /**
             * @description Endpoint do Web Push devolvido por PushManager.subscribe()
             * @example https://fcm.googleapis.com/fcm/send/…
             */
            endpoint: string;
            /** @description Chave pública da inscrição (base64url) */
            p256dh: string;
            /** @description Segredo de autenticação da inscrição (base64url) */
            auth: string;
            /** @example iPhone · Safari */
            plataforma?: string;
        };
        RemoverDeviceDto: {
            endpoint: string;
        };
        NotificacaoDto: {
            id: string;
            /** @example RESUMO_DIARIO */
            tipo: string;
            titulo: string;
            corpo: string;
            link: string | null;
            /** @example NORMAL */
            gravidade: string;
            /** Format: date-time */
            criadoEm: string;
            lida: boolean;
        };
        CaixaDeAvisosDto: {
            itens: components["schemas"]["NotificacaoDto"][];
            /** @description Contador do sino */
            naoLidas: number;
        };
        CriancaResumoDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2a 4m */
            idade: string;
            turmaNome?: string | null;
            alergias: string[];
        };
        MatriculaDto: {
            id: string;
            turmaId: string;
            turmaNome: string;
            /** @enum {string} */
            status: "ATIVA" | "TRANCADA" | "ENCERRADA" | "LISTA_ESPERA";
            /** @example 2026-02-01 */
            inicio: string;
            fim?: string | null;
        };
        CriancaNaListaDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2a 4m */
            idade: string;
            /** @example 2023-04-12 */
            dataNascimento: string;
            alergias: string[];
            matricula?: components["schemas"]["MatriculaDto"] | null;
            /** @description Responsáveis com vínculo ativo */
            responsaveis: number;
            arquivada: boolean;
        };
        CriarCriancaDto: {
            /** @example Sofia Prado */
            nome: string;
            /** @description Como a criança é chamada, se diferente do registro */
            nomeSocial?: string;
            /**
             * @description AAAA-MM-DD
             * @example 2023-04-12
             */
            dataNascimento: string;
            /**
             * @example [
             *       "Amendoim"
             *     ]
             */
            alergias?: string[];
            restricoesAlimentares?: string[];
            condicoesSaude?: string[];
            observacoesSaude?: string;
            /** @description Matricula na turma já no cadastro — evita a criança nascer sem turma */
            turmaId?: string;
        };
        ResponsavelDaCriancaDto: {
            id: string;
            nome: string;
            celular?: string | null;
            /** @example MAE */
            tipo: string;
            podeRetirar: boolean;
            podeAutorizar: boolean;
            /** @description Bloqueado por decisão judicial ou medida protetiva */
            bloqueado: boolean;
            /** @description Já abriu o app ao menos uma vez */
            ativou: boolean;
        };
        AutorizadoDto: {
            id: string;
            nome: string;
            documento: string;
            parentesco?: string | null;
            validoAte?: string | null;
            ativo: boolean;
        };
        MedicacaoDoDiaDto: {
            id: string;
            medicamento: string;
            dosagem: string;
            /** @example oral */
            via: string;
            /** @description ["10:00","16:00"] ou { seNecessario: true } */
            horarios: Record<string, never>;
            /** @example 2026-08-01 */
            inicio: string;
            /** @example 2026-08-10 */
            fim: string;
            observacoes?: string | null;
            /** @description Horários já administrados hoje — é o que diz se ainda falta dar */
            administradoHoje: string[];
        };
        ConsentimentoDto: {
            /** @enum {string} */
            escopo: "INTERNO" | "MATERIAL_DIVULGACAO" | "REDES_SOCIAIS";
            concedido: boolean;
            /** @description Nunca respondido pela família */
            semResposta: boolean;
            /** Format: date-time */
            decididoEm?: string | null;
        };
        FichaDaCriancaDto: {
            id: string;
            nome: string;
            nomeSocial?: string | null;
            /** @example 2023-04-12 */
            dataNascimento: string;
            /** @example 2a 4m */
            idade: string;
            alergias: string[];
            restricoesAlimentares: string[];
            condicoesSaude: string[];
            observacoesSaude?: string | null;
            arquivada: boolean;
            matricula?: components["schemas"]["MatriculaDto"] | null;
            responsaveis: components["schemas"]["ResponsavelDaCriancaDto"][];
            autorizados: components["schemas"]["AutorizadoDto"][];
            medicacoes: components["schemas"]["MedicacaoDoDiaDto"][];
            consentimentos: components["schemas"]["ConsentimentoDto"][];
        };
        AtualizarCriancaDto: {
            nome?: string;
            nomeSocial?: string | null;
            /** @example 2023-04-12 */
            dataNascimento?: string;
            alergias?: string[];
            restricoesAlimentares?: string[];
            condicoesSaude?: string[];
            observacoesSaude?: string | null;
        };
        ItemTimelineDto: {
            id: string;
            /** @enum {string} */
            categoria: "ENTRADA" | "SAIDA" | "REGISTRO" | "OCORRENCIA" | "MEDICACAO";
            /** @enum {string} */
            tipo?: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** Format: date-time */
            ocorridoEm: string;
            /** @description Frase pronta para exibição — a família não lê enum */
            titulo: string;
            detalhe?: string | null;
            dados: Record<string, never>;
        };
        DiaDaCriancaDto: {
            crianca: components["schemas"]["CriancaResumoDto"];
            /** @example 2026-08-02 */
            data: string;
            presente: boolean;
            ausente: boolean;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            timeline: components["schemas"]["ItemTimelineDto"][];
            /** @description Resumo em uma frase, para o card e a notificação */
            resumo: string;
            /** @description Medicação autorizada e vigente hoje — some da ficha quando a autorização vence */
            medicacoes: components["schemas"]["MedicacaoDoDiaDto"][];
        };
        DecidirConsentimentoDto: {
            /** @enum {string} */
            escopo: "INTERNO" | "MATERIAL_DIVULGACAO" | "REDES_SOCIAIS";
            /** @description false revoga o consentimento vigente */
            concedido: boolean;
        };
        MatricularDto: {
            criancaId: string;
            /** @description Se a criança já estiver ativa em outra turma, isto é uma transferência */
            turmaId: string;
        };
        MatriculaCompletaDto: {
            id: string;
            criancaId: string;
            turmaId: string;
            turmaNome: string;
            /** @enum {string} */
            status: "ATIVA" | "TRANCADA" | "ENCERRADA" | "LISTA_ESPERA";
            /** @example 2026-02-01 */
            inicio: string;
            fim?: string | null;
            /** @description Havia matrícula ativa em outra turma, que foi encerrada */
            transferida: boolean;
        };
        AtualizarMatriculaDto: {
            /** @enum {string} */
            status: "ATIVA" | "TRANCADA" | "ENCERRADA" | "LISTA_ESPERA";
        };
        HistoricoMatriculaDto: {
            id: string;
            turmaId: string;
            turmaNome: string;
            /** @enum {string} */
            status: "ATIVA" | "TRANCADA" | "ENCERRADA" | "LISTA_ESPERA";
            /** @example 2026-02-01 */
            inicio: string;
            fim?: string | null;
        };
        CheckinDto: {
            criancaId: string;
            turmaId: string;
            /** @description Quem entregou a criança na porta */
            entreguePorNome?: string;
            /** @description Marca falta em vez de presença */
            ausente?: boolean;
            justificativa?: string;
        };
        PresencaDto: {
            id: string;
            criancaId: string;
            /** @example 2026-08-02 */
            data: string;
            /** Format: date-time */
            entradaEm?: string | null;
            /** Format: date-time */
            saidaEm?: string | null;
            ausente: boolean;
            entreguePorNome?: string | null;
            retiradoPorNome?: string | null;
        };
        CheckoutDto: {
            criancaId: string;
            /** @description Quem retirou — conferido contra a lista de autorizados */
            retiradoPorNome: string;
            retiradoPorVinculoId?: string;
            retiradoPorAutorizadoId?: string;
        };
        EnvelopeRegistroDto: {
            /** @description UUID gerado no cliente — chave de idempotência */
            clientId: string;
            criancaId: string;
            turmaId: string;
            /** @enum {string} */
            tipo: "ALIMENTACAO" | "SONO" | "HIGIENE" | "HIDRATACAO" | "HUMOR" | "ATIVIDADE" | "OBSERVACAO";
            /** @example 2026-08-02T14:30:00.000Z */
            ocorridoEm: string;
            /** @description Payload específico do tipo, validado por Zod (ver schemas/) */
            dados: Record<string, never>;
            observacao?: string | null;
        };
        LoteSincronizacaoDto: {
            itens: components["schemas"]["EnvelopeRegistroDto"][];
        };
        ResultadoItemDto: {
            clientId: string;
            /**
             * @description "duplicado" é sucesso: é o reenvio normal de quem estava offline
             * @enum {string}
             */
            status: "criado" | "duplicado" | "erro";
            id?: string;
            codigo?: string;
            mensagem?: string;
        };
        ResultadoSincronizacaoDto: {
            resultados: components["schemas"]["ResultadoItemDto"][];
            criados: number;
            duplicados: number;
            erros: number;
        };
        ComunicadoDto: {
            id: string;
            titulo: string;
            corpo: string;
            /** Format: date-time */
            publicadoEm?: string | null;
            exigeCiencia: boolean;
            lido: boolean;
            /** @description Confirmações de leitura — o que a escola cobra */
            totalLeituras: number;
        };
        MarcarLidoDto: {
            criancaId: string;
        };
        CardapioDto: {
            id: string;
            /** @example 2026-08-03 */
            data: string;
            /**
             * @example {
             *       "lancheManha": "Fruta da estação",
             *       "almoco": "Arroz, feijão, frango e legumes"
             *     }
             */
            refeicoes: Record<string, never>;
        };
        CriarOcorrenciaDto: {
            /** @description UUID gerado no cliente — reenvio não cria uma segunda ocorrência */
            clientId: string;
            criancaId: string;
            /** @enum {string} */
            tipo: "FEBRE" | "QUEDA" | "MORDIDA" | "MACHUCADO" | "ALERGIA" | "VOMITO" | "CHORO_PROLONGADO" | "COMPORTAMENTO" | "OUTRO";
            /** @enum {string} */
            gravidade: "LEVE" | "MODERADA" | "GRAVE";
            /** @example 2026-08-06T18:20:00.000Z */
            ocorridoEm: string;
            /** @example Parque */
            local?: string;
            /** @description O que aconteceu */
            descricao: string;
            /** @description O que a escola fez — é isto que transforma o registro em prova de cuidado */
            conduta: string;
            /** @example 38.4 */
            temperatura?: number;
        };
        OcorrenciaDto: {
            id: string;
            criancaId: string;
            criancaNome: string;
            /** @enum {string} */
            tipo: "FEBRE" | "QUEDA" | "MORDIDA" | "MACHUCADO" | "ALERGIA" | "VOMITO" | "CHORO_PROLONGADO" | "COMPORTAMENTO" | "OUTRO";
            /** @enum {string} */
            gravidade: "LEVE" | "MODERADA" | "GRAVE";
            /** Format: date-time */
            ocorridoEm: string;
            local?: string | null;
            descricao: string;
            conduta: string;
            temperatura?: number | null;
            /** @description Frase pronta, no tom em que a família lê */
            titulo: string;
            /**
             * Format: date-time
             * @description Quando a família confirmou que leu — o que fecha o ciclo da comunicação
             */
            cienteEm?: string | null;
            /** @description Responsáveis avisados no registro */
            familiasAvisadas: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaudeController_saude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaudeController_pronto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEquipeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_convite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsarConviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    AuthController_sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSessaoDto"];
                };
            };
        };
    };
    DemoController_perfis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DemoController_entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoDto"];
                };
            };
        };
    };
    EscolasController_buscar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscolaDto"];
                };
            };
        };
    };
    EscolasController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarEscolaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscolaDto"];
                };
            };
        };
    };
    EscolasController_resumo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoEscolaDto"];
                };
            };
        };
    };
    UsuariosController_equipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembroEquipeDto"][];
                };
            };
        };
    };
    UsuariosController_responsaveis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criancaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsavelDto"][];
                };
            };
        };
    };
    UsuariosController_convites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteDto"][];
                };
            };
        };
    };
    UsuariosController_criarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarConviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteDto"];
                };
            };
        };
    };
    UsuariosController_familiasSemAcesso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriancaSemAcessoDto"][];
                };
            };
        };
    };
    TurmasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurmaDto"][];
                };
            };
        };
    };
    TurmasController_grade: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDoDiaDto"];
                };
            };
        };
    };
    TurmasController_fecharTurno: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FechamentoDto"];
                };
            };
        };
    };
    NotificacoesController_chavePublica: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChavePublicaDto"];
                };
            };
        };
    };
    NotificacoesController_registrarDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarDeviceDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificacoesController_removerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoverDeviceDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificacoesController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaixaDeAvisosDto"];
                };
            };
        };
    };
    NotificacoesController_marcarLida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificacoesController_marcarTodasLidas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificacoesController_teste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificacaoDto"];
                };
            };
        };
    };
    CriancasController_minhas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriancaResumoDto"][];
                };
            };
        };
    };
    CriancasController_listar: {
        parameters: {
            query?: {
                turmaId?: string;
                arquivadas?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriancaNaListaDto"][];
                };
            };
        };
    };
    CriancasController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarCriancaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriancaNaListaDto"];
                };
            };
        };
    };
    CriancasController_ficha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaDaCriancaDto"];
                };
            };
        };
    };
    CriancasController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarCriancaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaDaCriancaDto"];
                };
            };
        };
    };
    CriancasController_arquivar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaDaCriancaDto"];
                };
            };
        };
    };
    CriancasController_desarquivar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaDaCriancaDto"];
                };
            };
        };
    };
    CriancasController_dia: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaDaCriancaDto"];
                };
            };
        };
    };
    CriancasController_decidirConsentimento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecidirConsentimentoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentimentoDto"][];
                };
            };
        };
    };
    MatriculasController_matricular: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatricularDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatriculaCompletaDto"];
                };
            };
        };
    };
    MatriculasController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarMatriculaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatriculaCompletaDto"];
                };
            };
        };
    };
    MatriculasController_historico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criancaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricoMatriculaDto"][];
                };
            };
        };
    };
    PresencasController_checkin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"];
                };
            };
        };
    };
    PresencasController_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"];
                };
            };
        };
    };
    PresencasController_listar: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path: {
                turmaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresencaDto"][];
                };
            };
        };
    };
    RegistrosController_sincronizar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteSincronizacaoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoSincronizacaoDto"];
                };
            };
        };
    };
    ComunicadosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunicadoDto"][];
                };
            };
        };
    };
    ComunicadosController_marcarLido: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarLidoDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardapiosController_semana: {
        parameters: {
            query?: {
                data?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardapioDto"][];
                };
            };
        };
    };
    OcorrenciasController_listar: {
        parameters: {
            query?: {
                turmaId?: string;
                data?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcorrenciaDto"][];
                };
            };
        };
    };
    OcorrenciasController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarOcorrenciaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcorrenciaDto"];
                };
            };
        };
    };
    OcorrenciasController_confirmarCiencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcorrenciaDto"];
                };
            };
        };
    };
}
